### ISSUE TITLE
Feature Space: invFtrVec function

### ISSUE THREAD

**Issue by ErikNovak** [qminer/qminer#185]
Throws exception if parameter is a vector.
```
var ftr = new qm.FeatureSpace(base, { type: "numeric", source: "FtrSpaceTest", field: "Value" });
var ftrvec = ftr.ftrVec(Store[0]);
var vec = ftr.invFtrVec(ftrvec); // throws exception
```

**Comment by blazf** [comment]
Looks like this is already covered by the following passing test:

            var ftr = new qm.FeatureSpace(base, { type: "numeric", source: "FtrSpaceTest", field: "Value" });
            var ftrvec = ftr.extractVector(Store[0]);
            var vec = ftr.invertFeatureVector(ftrvec);
            assert.equal(vec.length, 1);
            assert.equal(vec.at(0), 1.0);
