### ISSUE TITLE
Rename of "docjs" directory to "docjs.todo" broke homepage example links

### ISSUE THREAD

**Issue by cpick** [qminer/qminer#203]
The links in the [examples section](http://qminer.ijs.si/#examples) of the QMiner homepage have been broken since the "docjs" directory was renamed "docjs.todo" in commit af8a084.

**Comment by cpick** [comment]
The links in the [wiki examples](https://github.com/qminer/qminer/wiki/Example) are also broken.

**Comment by blazf** [comment]
Removed or updated broken links.
