### ISSUE TITLE
Alerts on Continuous queries

### ISSUE THREAD

**Issue by KrishnaPG** [qminer/qminer#246]
Thank you for sharing this good work.

Trying to verify if this can be used for *alert when something interesting happens in a stream* scenario.

i.e., can some one "listen" to a stream for "data changes"?

For example, if last 3 values are greater than the mean of the of last 8 data points then raise an alert (emit event).

Or, instead of emitting an event, it could create a new data point in a child stream, so that who ever is "listening" on that child stream can see that data point and do whatever is necessary.

````
Base stream:  v1   v2   v3   v4   v5   v6   v7   v8 ....
child stream:    .     .     .      .      1     .      .   .....
````

I am looking for creating "user defined functions" as "alert triggering" mechanism on streams, so that user can define his own "monitoring" javascript function to know about interesting changes on his data.

Can this package achieve such things? Creating child streams and listening on child streams for data changes etc..?

Any pointers or example would be of great help.

**Comment by rupnikj** [comment]
Hi Krishna! 

In qminer it's easy to implement such a scenario. The idea is to create two stores (tables) - one for the sensor data and the other one for alerts. Then we can create a stream aggregate (a function that processes data which can be implemented in javascript) on the sensor store. The function is triggered for each new sensor measurement. If the alert is detected it could push it to the alert store. There we can define another stream aggregate which does something with it - that one represents your child stream.

In our framework the online data normalization (0 mean, 1 variance) is implemented as a feature extractor.

Stores, stream aggregates and feature extractors are all a part of the core qm module - see for API and simple examples: https://rawgit.com/qminer/qminer/master/nodedoc/module-qm.html

**Comment by KrishnaPG** [comment]
Thank you @rupnikj for the helpful response. Will check the example and the documentation.

**Comment by KrishnaPG** [comment]
While going through the examples, `store().addStreamAggr` method is accepting varying kinds of json object, some with `outStore, createStore` and some with `inAggr` etc. keys.

Where can I find info on this full list of all possible values for this json object (acceptable as param to the `addStreamAggr` method) and their meanings? Looks like the docs are not covering that part.

Anywhere in the code perhaps I can look?

**Comment by KrishnaPG** [comment]
Never mind. Looks like each in-built stream aggregate has its own kind of json definition and the documentation for each stream aggregate class is covering it. Thanks.
