### ISSUE TITLE
field join types that use other data types

### ISSUE THREAD

**Issue by gregorleban** [qminer/qminer#292]
Currently field joins use 8 bytes for storing record id and 4 bytes to store Fq. It would be helpful if this would be customizable. 
For storing record it it would be nice if storing using 4 bytes would be supported.
For storing record fq it would be good to support 0 byte, 1 byte and 4 bytes (as currently). In case of 0 bytes, the Fq would simply return 1 if join would exist and 0 otherwise.

**Comment by rupnikj** [comment]
closed by #362
