### ISSUE TITLE
prevent LIBSVM's internal functions from writing to stdout

### ISSUE THREAD

**Issue by rupnikj** [qminer/qminer#302]

**Comment by rupnikj** [comment]
void svm_set_print_string_function(void (*print_func)(const char *));

**Comment by blazs** [comment]
Using that function doesn't do the job because `svm.cpp` uses `printf` and `fprintf` all over the place.

**Comment by rupnikj** [comment]
I suggest parametrizing svm to use two PNotify objects and do two find/replace all
"fprintf(stderr," -> "ErrorNotify->OnStatusFmt("
"info(" -> "DebugNotify->OnStatusFmt("

Then from qminer you can initialize them with these two loggers:
TQm::TEnv::Error
TQm::TEnv::Debug

**Comment by rupnikj** [comment]
#338
