### ISSUE TITLE
TRecSet::GetSampleRecSet does not have SortedP parameter anymore

### ISSUE THREAD

**Issue by gregorleban** [qminer/qminer#367]
The new TRecSet does not support anymore having items with weights (fqs) and at the same time doing a random sampling where items would not be selected relative to the weights. Is there a particular reason for not supporting this anymore?

**Comment by blazf** [comment]
The option was removed when I was fixing how sampling works on wighted record sets. Will add it back.

**Comment by blazf** [comment]
Added `IgnoreFqP` parameter to `GetSampleRecSet` which tells it to ignore frequency information when available. Closed with PR #369
