### ISSUE TITLE
Segmentation fault when using a windowed store in a combination with a windowed stream aggregate

### ISSUE THREAD

**Issue by lstopar** [qminer/qminer#394]
When using a windowed store in a combination with a windowed stream aggregate and the length of the aggregates window is longer than the length of the stores window, QMiner crashes with a segmentation fault after calling base.garbageCollect()

**Comment by rupnikj** [comment]
TODO: add assert for valid record id in the window buffer and record buffer.
One option: make stream aggregates able to report which records are safe to delete.
