### ISSUE TITLE
cleanup linalg

### ISSUE THREAD

**Issue by rupnikj** [qminer/qminer#413]
- comments above function declarations
- IFDEFs should only be used in hpp and cpp files and not in the header file
- move template implementations to linalg.hpp and the other implementations to linalg.cpp
- TLAMisc, TLAUtil, TNumericalStuff: reorganize
- TVector, TFullMatrix: decide if we want to keep this? Change to a version without ownership (ref)
- TMatrix (black box methods) implementations should use TLinAlg static methods

**Comment by blazf** [comment]
We did lots of this already, @rupnikj can you check at Friday meeting what is still left do to and add it as a separate issue?
