### ISSUE TITLE
Reduce memory overhead per record due to size of `TMem`

### ISSUE THREAD

**Issue by blazf** [qminer/qminer#426]
Store with one `int` field containing 10M records (40MB of raw data) takes 120MB of disk space (80MB of overhead) and up to 700MB of memory.

Possible direct solutions:
- `TMem` uses more memory the needed: Introduction of `TMemBase` with virtual functions and of `Owner` member increased `sizeof(TMem)` from 20 bytes to 32 bytes. I suggest reverting `TMem` to as it was before commit 2f495af . This safes us 120MB of memory.
- We should have a dedicated class for storing records and not use TMem. Using only pointer to the buffer and the length of the buffer we get to 12 bytes per record, saving additional 80MB
- `TMem` saves both `MxLen` and `Len`. Former is not necessary for serialisation and could be omitted. This halves the storage overhead per record.
- We allocate memory for each record individually, introducing around 12-14 bytes of overhead per record. We could reduce the overhead by pooling fixed-width parts of records into larger blocks, reducing memory allocation overheads. We could also move some variable parts to fixed-with parts by putting an upper limit to their sizes, similar to VARCHAR(16) commands in DBs.
- Fixed width parts also do not need `TMem::Len` when serialising as their size is know, reducing serialisation overhead to 0MB.

@rupnikj @bergloman

**Comment by blazf** [comment]
Test code:

```
var qm = require('qminer');
var base = new qm.Base({
    mode: 'createClean',
    schema: [{ name: "Tesi", fields: [{ name: "val", type: "int" }] }]
});
var store = base.store("Tesi");
for (var i = 0; i < 1000000; i++) {
	store.push({val : i % 10});
}
base.close();
```

**Comment by bergloman** [comment]
I think the most significant change was that the data is stored in `TBlobBs` and no longer serialized as plain `TVec`. Each "blob" has an overhead  on disk - header + footer + size-difference up to next block size.

**Comment by blazf** [comment]
We did a test with making `TVec<TMem>` with exactly 10M elements and storing 4 bytes to each `TMem`. That already accounted for most of the memory usage:
- direct: `sizeof(TMem)` * 10M + `sizeof(int)` * 10M = 360MB
- indirect (due to OS memory management): ~12 bytes * 10M = 120MB

Together: 480MB or 440MB overhead + 40MB for actual integers

Memory overhead due to usage of `TBlobBs` for storing `TMem` on disk is negligible compared to above overhead, at least according to our (me and @rupnikj) counting.

One thing to note is that there is a bug in TMem reporting of its size:
- `sizeof(TMem)` = 32
- `TMem Mem; Mem.GetMemUsed() = 16`

**Comment by blazf** [comment]
The test snippet for `TMem`

```
TMem Mem;
printf("%d %d\n", (int)sizeof(TMem), (int)Mem.GetMemUsed());
const int N = 10*1000*1000;
TVec<TMem> ValV(N, 0);
for (int i = 0; i < N; i++) {
    TMem Mem;
     TRefMemOut(Mem).Save(i);
     IAssertR(Mem.Len() == 4, TStr::Fmt("%d != 4", Mem.Len()));
     ValV.Add(Mem);
}
printf("MEM %d %d %d\n", ValV.Len(), (int)ValV.GetMemUsed(), (int)ValV.GetMemUsedDeep());
```

**Comment by bergloman** [comment]
`sizeof(TMem)` is now 24 bytes, while `GetMemUsed()` returns 20.
