### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by rupnikj** [qminer/qminer#438]
```
FtrSpVec Tests
```

  ✓ should return a sparse vector for the first record in store: constant
  ✓ should return a sparse vector for the first record in store: random
  ✓ should return a sparse vector for the first record in store: numeric
  ✓ should return a sparse vector for the first record in store: categorical
  ✓ should return a sparse vector for the first record in store: multinomial
  ✓ should return a sparse vector for the first record in store: text
  ✓ should return a sparse vector for the first record in store: pair
  ✓ should return a sparse vector for the first record in store: jsfunc
  ✓ should return a sparse vector for the first record in store: two extractors
./test/nodejs/test.sh: line 9:  5014 Segmentation fault      (core dumped) mocha --timeout 30000 *.js

**Comment by blazf** [comment]
@rupnikj this issue appears to be fixed, can you confirm?

```
$ mocha featurespace.js --grep=two


  Feature Space Tests
    Dim Tests
      ✓ should return the dimension of the feature space, where it takes two extractors
    FtrVec Test
      ✓ should return a vector for the first record in store: two extractors
    FtrSpVec Tests
      ✓ should return a sparse vector for the first record in store: two extractors


  3 passing (200ms)
```

**Comment by rupnikj** [comment]
Looks like it's resolved.
