### ISSUE TITLE
TStr::SearchStr - change assertions

### ISSUE THREAD

**Issue by gregorleban** [qminer/qminer#443]
https://github.com/qminer/qminer/blob/master/src/glib/base/dt.cpp#L1601

TStr::SearchStr throws error if the string is empty. It is unnatural that we would have to have to have extra tests to prevent this in the user's code. I would suggest that we change

    EAssertR(BChN >= 0 && BChN < ThisLen, "TStr::SearchStr: index BChN out of bounds!");

simply to:

    if (BChN < 0 || BChN >= ThisLen) return -1;

Any comments?

**Comment by blazf** [comment]
I would only make exception for the case when ThisLen == 0 and BChN == 0.
```
if (BChN == 0 && ThisLen == 0) { return -1; }
```

For the rest, I would keep the assertion as it is.

@rupnikj -- any comment?

**Comment by rupnikj** [comment]
Fixed in #447
