### ISSUE TITLE
ParamVal->GetObjStr return by reference

### ISSUE THREAD

**Issue by ErikNovak** [qminer/qminer#459]
The method 

``` cpp
const TStr& TJsonVal->GetObjStr(const char *Key, const TStr& DefStr);
```

shouldn't return `TStr` by reference. In the use case

``` cpp
PJsonVal ParamVal = TJsonVal::NewObj();
const TStr& TypeNm = ParamVal->GetObjStr("type", "unicode");
```

the value `TypeNm` should be set to `"unicode"`, but really it's pointing to an empty address, because the string `"unicode"` has been destroyed. 

Probably similar issue occures with similar `TJsonVal->GetObj*` methods.

**Comment by andrejmuhic** [comment]
I think that is exactly the standard behavior of references to temporary objects according to C++ standard. Moreover references to temporary objects should be avoided. I think that this compiles
only in MSVS, g++ will complain that this is not valid.
To avoid this problem, maybe use this:
PJsonVal ParamVal = TJsonVal::NewObj();
const TStr TypeNm = ParamVal->GetObjStr("type", "unicode");
Or even better avoid using references to temporary objects.
