### ISSUE TITLE
critical issue in LoadBase()

### ISSUE THREAD

**Issue by gregorleban** [qminer/qminer#462]
If I'm not mistaken there is a critical bug in 

https://github.com/qminer/qminer/blob/master/src/qminer/qminer_storage.cpp#L5326

TStoreImpl constructor does not accept FAccess argument since it loads it from Base. Instead the FAccess value (usually 4) is used as store cache size:

https://github.com/qminer/qminer/blob/master/src/qminer/qminer_storage.cpp#L2960

**Comment by blazf** [comment]
Closed with #463
