### ISSUE TITLE
how to use HoeffdingTree C++ code as stand alone code

### ISSUE THREAD

**Issue by Sandy4321** [qminer/qminer#493]
I need to study
HoeffdingTree
how I can run C++ code

**Comment by blazs** [comment]
Hi @Sandy4321. Sorry for the huge lag, I have only now noticed the issue.

If you're still interested in running the code, you can, for starters, look at how `qminer/src/glib/mine/hoeffding.h` and `qminer/src/glib/mine/hoeffding.cpp` are used in `qminer/src/nodejs/ht/ht_nodejs.h`.

Feel free to ask for help, either here or via email, if you encounter further issues. Best, B.
